---
driver:
  name: vagrant
  driver_plugin: vagrant
  customize:
    cpus: 2
    memory: 2048
    ## WORKAROUND: Windows - disable virtualbox consolelog on vagrant for WSL
    uartmode1: disconnected

platforms:
  - name: generic/ubuntu1804
  ## Uncomment to test on other platforms
  # - name: generic/ubuntu1810
  # - name: generic/ubuntu1604

provisioner:
  name: ansible_playbook
  ansible_cfg_path: /tmp/kitchen/ansible.cfg
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_inventory: inventory/hosts
  ansible_verbose: true
  # ansible_verbosity: debug
  ansible_verbosity: info
  ansible_version: 2.4.4.0
  env_vars:
    ## Human-readable output for ansible 2.4
    ANSIBLE_STDOUT_CALLBACK: debug
  idempotency_test: true
  additional_copy_path:
    - ansible.cfg
  recursive_additional_copy_path:
    # - inventory
    - roles.galaxy
    - roles
    - test
  require_ansible_omnibus: true
  require_ansible_repo: false
  require_chef_for_busser: false
  require_ruby_for_busser: true
  requirements_path: requirements.yml
  # roles_path: roles.galaxy:roles
  update_package_repos: true

verifier:
  name: serverspec
  default_pattern: true
  extra_flags: '-I /tmp/verifier/suites/serverspec'

suites:
  - name: automation
    driver_config:
      network:
        - ["forwarded_port", {guest: 25565, host: 25565}]  # Minecraft
        - ["forwarded_port", {guest: 8080, host: 8080}]  # Jenkins
    provisioner:
      playbook: playbook.yml
      hosts: automation
