---
## To override default driver in .kitchen.yml invoke with:
## KITCHEN_LOCAL_YAML=.kitchen_ec2.yml kitchen list
driver:
  name: ec2
  provider: aws
  region: us-west-2
  aws_ssh_key_id: testkitchen-us-west-2
  # iam_profile_name:
  instance_type: m3.medium

  tags:
    Name: test-kitchen
    ## `export HOSTNAME` to make it visible
    User: <%= ENV['USER'] %>@<%= ENV['HOSTNAME'] %>

transport:
  name: rsync
  ssh_key: <%= ENV['HOME'] %>/.ssh/keys/testkitchen-us-west-2.pem
  connection_timeout: 5
  connection_retries: 2

platforms:
  - name: ubuntu-16.04
    driver_config:
      image_search:
        owner-id: "099720109477"
        name: ubuntu/images/*/ubuntu-xenial-16.04-amd64-server-*

  - name: ubuntu-14.04
    driver_config:
      image_search:
        owner-id: "099720109477"
        name: ubuntu/images/*/ubuntu-trusty-14.04-amd64-server-*

  - name: debian9
    driver_config:
      image_search:
        owner-id: "379101102735"
        name: debian-stretch-amd64-hvm-*

  - name: debian8
    driver_config:
      image_search:
        owner-id: "379101102735"
        name: debian-jessie-amd64-hvm-*
