source 'https://rubygems.org'

gem 'guard'
gem 'guard-kitchen'
gem 'kitchen-sync'
gem 'kitchen-transport-rsync'
gem 'kitchen-ansible'
gem 'kitchen-ec2'
gem 'kitchen-vagrant'
gem 'kitchen-verifier-serverspec'
gem 'test-kitchen'
gem 'vagrant-wrapper'
