FROM openjdk:8-jre
WORKDIR /app
VOLUME /app
EXPOSE 25565
COPY . /app
RUN echo true > /app/eula.txt
RUN echo true > eula.txt
RUN java -jar craftbukkit.jar
CMD echo eula=true > /app/eula.txt && java -Xmx1024M -Xms1024M -jar craftbukkit.jar nogui --noconsole

