---

- name: Ensure build dir for {{ item.name }}
  file: 
    path: app/{{ item.name }}
    state: directory
    mode: 0755

- name: Download app_jarfiles for {{ item.name }}
  get_url:
    url: "{{ item.url }}"
    dest: app/{{ item.name}}/{{ item.jarfile }}

- name: Deploy dockerfile for {{ item.name }}
  template:
    src: Dockerfile.j2
    dest: app/{{ item.name }}/Dockerfile
    mode: 0644
  register: df

- name: Build container for {{ item.name }}
  docker_image:
    name: "{{ item.name }}"
    path: app/{{ item.name }}
    force: "{{ df|changed }}"
    # buildargs:
    #   listen_port: 25565

- name: Launch container for {{ item.name }}
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.name }}"
    state: started
    volumes: "{{ item.name }}:/app:rw"
    published_ports: "{{ item.published_ports | default('') }}"
